### ISSUE TITLE
Bug involving War Dirigible being blanked

### ISSUE THREAD

**Issue by SwigganA38** [fantasy-realms/fantasy-realms.github.io#10]
Hi!

I had asked a question on BGG, that Bruce Glassco responded to, and I think it may clear up some confusion about what happens when single words are cleared from a penalty. [Here's the thread over there.](https://boardgamegeek.com/thread/2695268/more-fun-rangers-and-blimps) 

Basically, his answer verified that in [this](https://fantasy-realms.github.io/index.html?hand=FR45,FR25,FR49+FR49:FR25:flame) situation, the War Dirigible should NOT be blanked due to a lack of an Army, even if the Rangers have been suit-changed by Book of Changes. The Rangers clear "army" from the Dirigible's penalty, and since that's the only specific word in the penalty at all, that part of the penalty goes away completely. 

I'm not sure, but could this possibly be related to other issues involving the Dirigible as well? (There's another open issue with a couple of examples that include the Dirigible, but I don't know if they're connected to this one)

Anyway, thought that tidbit from Bruce might be useful.

**Comment by jpraet** [comment]
Thanks, this should be fixed now. You may need to clear your browser cache.
