### ISSUE TITLE
Collector Calculation - Wild Suits

### ISSUE THREAD

**Issue by jjdoyle623** [fantasy-realms/fantasy-realms.github.io#11]
As long as I am understanding the rules correctly – The Collector does not properly account for the suit change of the wild cards (Doppelgänger, Shapeshifter, Mirage).

Edit: I see the problem now. "Different" cards are not not two different physical cards, but two cards with different names.

**Comment by spixi** [comment]
![result](https://user-images.githubusercontent.com/3192596/130611527-9067eb04-b4c6-437e-8e6e-e3bcbe3e42b0.png)
I reopen that issue, because it seems that the app handles Doppelgänger differently. I don’t now which one is correct.

**Comment by jpraet** [comment]
This is a mistake in the mobile app (which is no longer updated). Here's a message from the designer of the game:
https://boardgamegeek.com/thread/1838508/article/26773487#26773487

Note that he mentions that you _can_ use it with Mirage and Shapeshifter. In my opinion he means the Collector counts those, but still only if you use them as a card that's not already contained in your hand.
