### ISSUE TITLE
Ignore fbclid parameter and consider escaped GET parameters

### ISSUE THREAD

**Issue by spixi** [fantasy-realms/fantasy-realms.github.io#12]
If you want to share your result at Facebook by copying the link, Facebook escapes the parameters and adds an additional GET parameter with the name fbclid, which causes that no cards appear.

For example, the URI https://fantasy-realms.github.io/index.html?hand=FR06,FR08,FR09,FR10,FR11,FR26,FR53+FR53:FR08
becomes https://fantasy-realms.github.io/index.html?hand=FR06%2CFR08%2CFR09%2CFR10%2CFR11%2CFR26%2CFR53%20FR53%3AFR08&fbclid=IwAR14bG2EenX9TKKVX07Z_PRxd4ozKieeS-s9kK5-0KpdO5MWgXdkt4JLizw

The fbclid parameter should be ignored and escaped parameters should be considered.

**Comment by jpraet** [comment]
Should be ok now.
