### ISSUE TITLE
Issue with War Dirigible and Smoke

### ISSUE THREAD

**Issue by 72mal72** [fantasy-realms/fantasy-realms.github.io#13]
Hi,

I see different calculations depending of the entry order of the cards: 

1. War Dirigible and Smoke afterwards (and an Army) leads to a blanked War Dirigible, which is (in my opinion) wrong (https://fantasy-realms.github.io/index.html?hand=FR21,FR45,FR13+).
2. Smoke and War Dirigible afterwards (and an Army) leads to a non-blanked War Dirigible, which is (in my opinion) corrrect (https://fantasy-realms.github.io/index.html?hand=FR21,FR13,FR45+).

I assume that in the first case the War Dirigible is blanked because Smoke is not yet blanked, while in the second case the Smoke is already blanked.

Many thanks for checking and kind regards
Thomas

**Comment by jpraet** [comment]
You're correct. I'll see what I can do. The blanking logic has caused me a lot of headaches already 😕.
Often when I try to fix one thing it breaks another thing.

**Comment by jpraet** [comment]
It should be fixed now. I hope I didn't break anything else.

**Comment by 72mal72** [comment]
Many thanks, this works now! :-)
