### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by mbillard** [fantasy-realms/fantasy-realms.github.io#18]
Is this being worked on?

If I want to help with this effort, do I only need to update the language switcher and create a file in `i18n`?

**Comment by jpraet** [comment]
Hi, it's not being worked on yet. Contributions are welcome.

This is what is needed for adding an additional language:
* create i18n/Messages_fr.properties
* update language selector in index.html
* update languages variable in js/app.js
* add i18n/Messages_fr.properties entry to fantasy-realms.appcache and service-worker.js
