### ISSUE TITLE
Fantasy Realms - Scoring App Issue

### ISSUE THREAD

**Issue by 88MatteoB** [fantasy-realms/fantasy-realms.github.io#2]
Hi,

I wish to report an issue with the new scoring app available at http://wizkids.io/FRApp

If you have MIRAGE or SHAPESHIFTER and if you click on their "use" bottom, you'll be in a window where you need to select the target card to copy.
If at this point, by misclick, you click again on Mirage or Shapeshifter (removing them by your hand) you will be stuck in that selection window and the only way to go back is clicking on the "Reset" bottom, forcing you to start selecting the cards from the beginning.

A similar issue happens when you click on the "use" bottom of the BOOK OF CHANGES when you have no other card in your hand.

There might be cards with similar issues with their "Use" button in the two expansion blocks.
For example I've noticed that, after using the ANGEL ability on another card, if I try then to remove this last card the app is somehow freezed.

Thanks for your support.
Take care. 

Matteo

**Comment by jpraet** [comment]
This should also be fixed. All card actions now have a "Cancel" button.
