### ISSUE TITLE
Two Mirages in hand

### ISSUE THREAD

**Issue by Mcklp** [fantasy-realms/fantasy-realms.github.io#20]
The "Fantasy Realms: The Cursed Hoard" adds second Mirage (and maybe Shapeshifter) and counting app only alows to add one to your hand. Maybe its written in the rules that you can have only one, but i didnt find it and at this moment. For me it looks like bug.

**Comment by jpraet** [comment]
Hi. Those cards are not added, they replace the base game cards.

![image](https://user-images.githubusercontent.com/2212615/139537155-78f0e49d-00f1-4605-8355-d2c00017e317.png)
