### ISSUE TITLE
Online multiplayer version planned?

### ISSUE THREAD

**Issue by duc-gp** [fantasy-realms/fantasy-realms.github.io#24]
Hello,

are there any plans for a online multiplayer version? If not, is there any chance I'm allowed to build one?

best regards,
duc

**Comment by jpraet** [comment]
Hi, no plans for an online version as far as I know.
I'll reach out to my contact at WizKids to ask if there are any objections to you building one.

**Comment by jpraet** [comment]
Unfortunately they cannot currently comment on what they might have in the works, nor give permission for building an unaffiliated online version of the game.

**Comment by duc-gp** [comment]
Happy new year! Alright thanks for letting me know so quickly. That's unfortunate but understandable. I hope you have plans for implementing something or in case you changed your mind or have any ideas on working together feel free to reach out any time.

Best
Duc
