### ISSUE TITLE
Should Doppelgänger duplicate the color changed by Book of changes?

### ISSUE THREAD

**Issue by apriljunge** [fantasy-realms/fantasy-realms.github.io#27]
**Book of changes** is used to change **War dirigibles** color to **Beast**.
Then this modified card is cloned by **Doppelgänger**. But the color of the duplicated card is the original color of Book of changes (Weapon), not the modified color (Beast).
This is why **Beastmaster** clears the penalty of the original War dirigibles, not the copied one.
Is this behavior intended? Or should Doppelgänger copy the modified color and be Beast instead?

https://fantasy-realms.github.io/index.html?hand=FR45,FR49,FR27,FR53+FR49:FR45:beast,FR53:FR45

**Comment by jpraet** [comment]
The Doppelgänger effect takes place before the Book of Changes, see this excerpt from the rule book:

![afbeelding](https://user-images.githubusercontent.com/2212615/164884228-0aa2c0e7-d877-487d-935f-f027a22623db.png)

**Comment by apriljunge** [comment]
Thank you! We somehow missed this part of the rule book ☺️
