### ISSUE TITLE
Great Flood, Cavern and Smoke

### ISSUE THREAD

**Issue by Nereos314** [fantasy-realms/fantasy-realms.github.io#30]
Great Flood blocks Cavern (as Land) such that the Bonus should no longer apply (Clears all penalties on Wheather). However, the 27 points from Smoke still count, although there is no flame.

**Comment by jpraet** [comment]
Clearing of penalties happens before blanking. From the rulebook:

![image](https://user-images.githubusercontent.com/2212615/182120176-ca4935f2-9c4a-4630-982b-da21cfe1af81.png)
