### ISSUE TITLE
"Phoenix" promo card

### ISSUE THREAD

**Issue by JGoutin** [fantasy-realms/fantasy-realms.github.io#33]
There is a "Phoenix" promo card that is missing.

This card exists in multiple languages: https://boardgamegeek.com/boardgame/347476/fantasy-realms-phoenix/versions

**Comment by jpraet** [comment]
This promo card is also included in the deluxe edition of the game, but it has a different card text:

![image](https://user-images.githubusercontent.com/2212615/185160531-91afdb20-de17-4ca7-8673-91599d88f7ae.png)

**Comment by jpraet** [comment]
The deluxe version of the card has been added in #35.
I will reach out to WizKids to ask if the card text of the deluxe version is to be considered as an errata to the previous version.
