### ISSUE TITLE
Infinite blanking loop

### ISSUE THREAD

**Issue by KingSupernova31** [fantasy-realms/fantasy-realms.github.io#37]
Add to your hand Wildfire, Fire Elemental, Great Flood, Blizzard, and Book of Changes. ([Here's a link](https://fantasy-realms.github.io/index.html?expansions=ch_suits&playerCount=4&hand=FR12,FR16,FR20,FR49,CH18+).) Use Book of Changes to change Blizzard into a Beast.

This results in a `RangeError: Maximum call stack size exceeded`, and the result is incorrect. (The rulebook doesn't directly address this type of 3-card loop, but I suspect they should all be blanked like Doppelgänger + Basilisk.)

The loop appears to occur at the line `if (by === target || (card.blanks !== undefined && card.blanks(by, this)) || !this._cardBlanked(by, target)) {`. This is part of the `_cardBlanked` function, which it calls recursively on itself, and it never exits.

**Comment by KingSupernova31** [comment]
Here's a direct link to the issue:

https://fantasy-realms.github.io/index.html?expansions=ch_suits&playerCount=4&hand=FR12,FR16,FR20,FR49,CH18+

**Comment by jpraet** [comment]
Thanks. The card blanking logic is quite complicated and indeed not very well specified in the rules.
It is difficult to get all the corner-cases working as expected.

I assume this is not a real in-game hand though, and you are just messing around a bit with the app?

**Comment by KingSupernova31** [comment]
It came up in a real game, though not quite this hand. I'm working on a program that can play Fantasy Realms, so it considers several hands similar to its current one that would be legal for it to move to, and it froze when it considered this hand.

**Comment by jpraet** [comment]
This should be fixed with #51.
