### ISSUE TITLE
Blanked Leprechaun/Genie/Necromancer

### ISSUE THREAD

**Issue by 88MatteoB** [fantasy-realms/fantasy-realms.github.io#4]
Hi,

According to the Cursed Horde rulebook, the first step of the Game End Sequence should be
as follow.

1. First, the Leprechaun, then the Genie, and finally the Necromancer may draw new cards

This should happen BEFORE any penalty effect.
But in the scoring app, if any of these cards get blanked, the player is not allowed to choose the related extra card.

Is it possible to fix that?
Thank you for your support.

Matteo

**Comment by 88MatteoB** [comment]
I've noticed though that, if the 8th ot 9th card is added on the app BEFORE the cards in the object get blanked, the added cards remain selected and are correctly scored.
So this might not be an issue. 👍

**Comment by 88MatteoB** [comment]
That said, it would probably be better if the blanking of Leprechaun/Genie/Necromancer doesn't bring back, on the scoring App, the maximum amount of cards in the hand from 9 to 8 (or from 8 to 7 if playing without the expansion).

wizkids.io/FRApp

Example:
- Wildfire could blank Leprechaun or Genie
- Demon could blank Necromancer

**Comment by jpraet** [comment]
This should be fixed now. You may need to do a hard refresh in your browser to get the updated version.
