### ISSUE TITLE
World Tree bonus can be incorrect when Phoenix Promo is blanked

### ISSUE THREAD

**Issue by eliburke** [fantasy-realms/fantasy-realms.github.io#41]
I'm playing around building an iPad version of this fine code and after a lot of 2nd guessing at the handling of Phoenix vs Phoenix Promo I believe I found a bug: 

Add World Tree, Phoenix Promo, and Unicorn. World Tree is worth 2 (no bonus)
Add Swamp or another Flood card. World Tree is worth 52 because Phoenix Promo is blanked.
Except Phoenix Promo retains its Suits per card text. 

Fix is in Deck.js line 734: you need another PHOENIX_PROMO special case.

**Comment by jpraet** [comment]
World Tree card text is "+50 if every non-BLANKED card is a different suit."

So even though a blanked Phoenix Promo retains its suits, I believe it should not impact the World Tree because it only cares about non-blanked cards.

**Comment by eliburke** [comment]
Ugh. That's a completely logical interpretation and I can't disagree. 
Thanks for the explanation.
