### ISSUE TITLE
Request for Permission to Contribute Korean Translation to Fantasy Realm Web Calculator Repository

### ISSUE THREAD

**Issue by bluekms** [fantasy-realms/fantasy-realms.github.io#48]
I would like to contribute a Korean translation to the Fantasy Realm web calculator repository.
May I have permission to submit a pull request (PR) with the translation?
Please advise on the preferred delivery method, if any.

Thank you for your consideration.

**Comment by jpraet** [comment]
Hi, isn't Korean language already available? See https://github.com/fantasy-realms/fantasy-realms.github.io/pull/29

Or do you wish to add the translations for the Cursed Hoard expansion?

**Comment by bluekms** [comment]
@jpraet yes. I opened pr.

thanks

**Comment by jpraet** [comment]
Thanks, the PR has been merged.
