### ISSUE TITLE
Undead Scoring Issue

### ISSUE THREAD

**Issue by 88MatteoB** [fantasy-realms/fantasy-realms.github.io#5]
Hi,

I wish to report a minor bug I've noticed when I use the Fantasy Realms Scoring App with the expansion mode ON.

Here, after selecting an Undead card, I usually can select which cards are in the "Discard area" to calculate the score of the Undead cards in the hand.
For example if I select the Dragon in the "Discard Area" then the Ghoul in my hand will get 4 points.

However, following the previous example, if I then select the Dragon for my hand it will not be anymore in the discard area (which is correct) but the Ghoul will keep scoring the extra 4 points as if the Dragon is still in the discard area.

The same issue happens with any type of card in the "Discard Area" giving points to any Undead card.

I've noticed that usually this scoring error gets automatically corrected if I add or remove other cards in the hand but it might be worth fixing it anyway.

Thanks. 
Matteo

**Comment by jpraet** [comment]
This should be working correctly now.
