### ISSUE TITLE
Application will not load cards or any information on multiple devices as of 08/10/2024.

### ISSUE THREAD

**Issue by stoutpanda** [fantasy-realms/fantasy-realms.github.io#59]
![fantasy Relams](https://github.com/user-attachments/assets/3501533d-4846-47b1-80d6-621f573fd311)

Fantasy Realms, on github pages.io will not load correctly on multiple browsers, devices and operating systems. 

Android,  IOS, Windows 11. Safari, Firefox, Chrome and Edge (latest versions for listed OS). 

JS error in browser console: 

Uncaught SyntaxError: missing } after property list
[app.js:26:3](https://fantasy-realms.github.io/js/app.js)note: { opened at line 15, column 17[app.js:15:17](https://fantasy-realms.github.io/js/app.js)

​
Also, have noted a missing , in the var languages list in app.js

**Comment by stoutpanda** [comment]
#58 This update at least added the issue with the languages variable. I don't know enough beyond that to help, I did submit a pull request to address that minor issue.

**Comment by stoutpanda** [comment]
https://stoutpanda.github.io/fantasy-realms.github.io/index.html  <- With the pull request issue is resolved. If you merge it all should be good.

**Comment by jpraet** [comment]
Thanks
