### ISSUE TITLE
Phoenix and Great Flood - Blanking

### ISSUE THREAD

**Issue by Diehtus** [fantasy-realms/fantasy-realms.github.io#62]
If I am interpreting this correctly, the Great Flood should not blank the Phoenix because the penalty was cleared by the Beastmaster?

<img width="795" alt="Bildschirmfoto 2024-10-11 um 11 20 03" src="https://github.com/user-attachments/assets/66568370-7777-46c9-b990-76d7bab33fac">

**Comment by jpraet** [comment]
The Phoenix is blanked not because of the "with any Flood", but because the Great Flood blanks Flames and Phoenix "Also counts as a Flame".

**Comment by Diehtus** [comment]
Hi thanks you for the fast answer. 
But Phoenix can not be blanked by any other Card, right?

**Comment by jpraet** [comment]
Oh, right.. so something seems wrong indeed. I will look into it.

**Comment by jpraet** [comment]
Should be OK now:

![image](https://github.com/user-attachments/assets/d8c425db-ac69-4dfe-a92c-0406f7da3e66)
