### ISSUE TITLE
URL does not account for added card

### ISSUE THREAD

**Issue by sultan** [fantasy-realms/fantasy-realms.github.io#67]
A hand with the Collector + two families triggers twice instead of once

Steps to reproduce:
* Start with this hand [Collector](https://fantasy-realms.github.io/index.html?expansions=ch_items,ch_suits&playerCount=6&hand=FR14,FR11,CH18,FR10,CH17,FR07,FR26,FR09,FR15,CH46+)
* Add Air Elemental

2 bugs
* Collector triggers twice instead of once and score is 403 when it should be 393
* URL does not account for added Air Elemental, then i was not able to share it with devs

**Comment by jpraet** [comment]
Hi. Collector can score multiple sets. Confirmed by the game author [here](https://boardgamegeek.com/thread/1864038/multiple-runs-with-gem-of-order-or-collector).

**Comment by sultan** [comment]
Good to know ! thanks for such dedication.
I renamed the bug to URL bug

**Comment by jpraet** [comment]
This should be fixed ([example](https://fantasy-realms.github.io/index.html?expansions=ch_items,ch_suits&playerCount=6&hand=CH46,FR14,FR11,CH18,FR10,CH17,FR07,FR26,FR09,FR15+)).
