### ISSUE TITLE
Treasure chest inconsistency

### ISSUE THREAD

**Issue by gfaugere** [fantasy-realms/fantasy-realms.github.io#69]
The Treasure Chest cursed item is worth -5 points.    
It's text mentions that it is "Worth +25 points if you have at least three other Cursed Items" – it should then be accounted for 25 points when the condition is met   
However the calculator applies -5+25, and totals at 20 points

**Comment by jpraet** [comment]
Hi. I posed that question to the designer when I was implementing the app, as it wasn't clear to me either.

He replied as follows: "It should end up -5 +25, or in other words 20. It would have been explicit if it was intended to replace the value."

**Comment by gfaugere** [comment]
Okay! Presence of the word "Worth" on the card makes this ambiguous IMO, thanks for the clarification :)
