### ISSUE TITLE
Weird bug with Book of Changes and Angel

### ISSUE THREAD

**Issue by BabyGrootTheEpic** [fantasy-realms/fantasy-realms.github.io#7]
I found a few odd bugs that can occur with Book of Changes, Angel, and either Blizzard & Great Flood or Rainstorm & Wildfire.
- In [this](https://fantasy-realms.github.io/index.html?expansions=ch_suits&playerCount=4&hand=FR49,FR12,CH18+FR49:FR12:building) hand if Book of Changes changes Blizzard into a suit that Great Flood blanks and you try to add Angel to the hand, it won't be, and no other cards can be added to the hand until one of the three cards is removed or Book of Changes' use button is pressed (then all the cards you tried to add will appear).

- In [this](https://fantasy-realms.github.io/index.html?expansions=ch_suits&playerCount=4&hand=FR49,FR12,CH18,CH08+) hand if Angel isn't being used on Blizzard and you try to use Book of Changes to change Blizzard into a suit that Great Flood blanks, then depending the order you used Book of Changes, a bug will happen.
If you clicked on the suit first, the sidebar will return to normal (and card cannot be added similar to the first bug), but Blizzard's suit won't have changed and the next card you click on (that isn't Book of Changes or Blizzard) will be changed into that suit.
If you clicked on Blizzard first, then nothing will happen when you click one of the suits Great Flood blanks.

Both bugs have the same results if you replace Blizzard with Rainstorm and Great Flood with Wildfire (and probably any other pair of cards where one naturally blanks the other).

**Comment by jpraet** [comment]
Thanks for the clear bug report. This issue should be fixed now.
