### ISSUE TITLE
Multiple versions on the web

### ISSUE THREAD

**Issue by KingSupernova31** [fantasy-realms/fantasy-realms.github.io#8]
If I search Google for "fantasy realms scoring app", this one comes up: https://jpraet.github.io/fantasy-realms/

However it looks like there's a second website at https://fantasy-realms.github.io/index.html

It looks like they're also using slightly different codebases, and one has bugs that are fixed in the other one. For example, [here](https://fantasy-realms.github.io/index.html?hand=FR08,FR12,FR16,FR49+FR49:FR12:beast) is a situation working correctly at fantasy-realms.github.io, while [here](https://jpraet.github.io/fantasy-realms/index.html?hand=8,12,16,49+49:12:Beast) is the same situation bugged on jpraet.github.io.

Would it be better to have one site redirect to the other?

**Comment by jpraet** [comment]
Good idea, it's done.

FYI:
https://jpraet.github.io/fantasy-realms/ was created under my personal github account.
I then worked together with WizKids on incorporating the Cursed Hoard expansion, and moved it to https://fantasy-realms.github.io/.

**Comment by KingSupernova31** [comment]
Same issue with new urls, now it's https://wizkids.com/fantasy-realms/ and https://fantasy-realms.github.io/. The second one seems to be slightly more up-to-date, as it has Phoenix.

**Comment by jpraet** [comment]
Hmm, I actually don't think the https://wizkids.com/fantasy-realms/ was supposed to serve the scoring app.
It is probably supposed to show the main information about the game, just like these:
* https://wizkids.com/fantasy-realms-deluxe-edition/
* https://wizkids.com/fantasy-realms-the-cursed-hoard/

I will check with my contact at wizkids. Thanks.
